net_kwargs:
  backbone: vit_tiny_patch16_384
  d_model: 192
  decoder:
    drop_path_rate: 0.0
    dropout: 0.1
    n_cls: 
    n_layers: 2
    name: mask_transformer
  distilled: false
  drop_path_rate: 0.1
  dropout: 0.0
  image_size: 
  n_cls: 
  n_heads: 3
  n_layers: 12
  normalization: vit
  patch_size: 16